2024-01-25 14:19:52,940 - process_api - INFO - run schema: "login"
2024-01-25 14:19:52,940 - process_api - INFO - run process: "main"
2024-01-25 14:19:52,940 - process_api - INFO - run step: "start"
2024-01-25 14:19:52,940 - process_api - INFO - perform navigate: ${state.server}
2024-01-25 14:20:36,504 - process_api - ERROR - Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=118.0.5993.70)
Stacktrace:
	GetHandleVerifier [0x00007FF73A708EF2+54786]
	(No symbol) [0x00007FF73A675612]
	(No symbol) [0x00007FF73A52A64B]
	(No symbol) [0x00007FF73A5263F3]
	(No symbol) [0x00007FF73A51971C]
	(No symbol) [0x00007FF73A51A977]
	(No symbol) [0x00007FF73A519B13]
	(No symbol) [0x00007FF73A518B8E]
	(No symbol) [0x00007FF73A518B33]
	(No symbol) [0x00007FF73A5173AA]
	(No symbol) [0x00007FF73A517CA3]
	(No symbol) [0x00007FF73A52CA5F]
	(No symbol) [0x00007FF73A5A5077]
	(No symbol) [0x00007FF73A58BE6A]
	(No symbol) [0x00007FF73A5A4D02]
	(No symbol) [0x00007FF73A58BC43]
	(No symbol) [0x00007FF73A560941]
	(No symbol) [0x00007FF73A561B84]
	GetHandleVerifier [0x00007FF73AA57F52+3524194]
	GetHandleVerifier [0x00007FF73AAAD800+3874576]
	GetHandleVerifier [0x00007FF73AAA5D7F+3843215]
	GetHandleVerifier [0x00007FF73A7A5086+694166]
	(No symbol) [0x00007FF73A680A88]
	(No symbol) [0x00007FF73A67CA94]
	(No symbol) [0x00007FF73A67CBC2]
	(No symbol) [0x00007FF73A66CC83]
	BaseThreadInitThunk [0x00007FFBFFD4257D+29]
	RtlUserThreadStart [0x00007FFC00F8AA58+40]

2024-01-25 14:20:36,504 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 37, in goto
    await goto(selenium_driver, url)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\navigate.py", line 3, in goto
    driver.get(url)
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=118.0.5993.70)
Stacktrace:
	GetHandleVerifier [0x00007FF73A708EF2+54786]
	(No symbol) [0x00007FF73A675612]
	(No symbol) [0x00007FF73A52A64B]
	(No symbol) [0x00007FF73A5263F3]
	(No symbol) [0x00007FF73A51971C]
	(No symbol) [0x00007FF73A51A977]
	(No symbol) [0x00007FF73A519B13]
	(No symbol) [0x00007FF73A518B8E]
	(No symbol) [0x00007FF73A518B33]
	(No symbol) [0x00007FF73A5173AA]
	(No symbol) [0x00007FF73A517CA3]
	(No symbol) [0x00007FF73A52CA5F]
	(No symbol) [0x00007FF73A5A5077]
	(No symbol) [0x00007FF73A58BE6A]
	(No symbol) [0x00007FF73A5A4D02]
	(No symbol) [0x00007FF73A58BC43]
	(No symbol) [0x00007FF73A560941]
	(No symbol) [0x00007FF73A561B84]
	GetHandleVerifier [0x00007FF73AA57F52+3524194]
	GetHandleVerifier [0x00007FF73AAAD800+3874576]
	GetHandleVerifier [0x00007FF73AAA5D7F+3843215]
	GetHandleVerifier [0x00007FF73A7A5086+694166]
	(No symbol) [0x00007FF73A680A88]
	(No symbol) [0x00007FF73A67CA94]
	(No symbol) [0x00007FF73A67CBC2]
	(No symbol) [0x00007FF73A66CC83]
	BaseThreadInitThunk [0x00007FFBFFD4257D+29]
	RtlUserThreadStart [0x00007FFC00F8AA58+40]


2024-01-25 14:20:36,706 - process_api - INFO - Task 0b045629-0ab0-49ec-951c-16c905c90423 completed in 00:00:43:564
